wandb_version: 1

data:
  desc: null
  value:
    train_dir: ../dcnn-data/train
    val_dir: ../dcnn-data/val
    batch_size: 32
    num_workers: 4
transforms:
  desc: null
  value:
    img_size: 256
    fs: 10
    min_num_jumps: 1
    max_num_jumps: 1
    max_silence_s: 8
model:
  desc: null
  value:
    hidden_channels:
    - 16
    - 32
    - 64
train:
  desc: null
  value:
    num_epochs: 10
    lr: 0.001
    weight_decay: 0
    device: cuda
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699868524.719607
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
